ALTER TABLE "Table"
ADD COLUMN "x" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "y" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "width" DOUBLE PRECISION NOT NULL DEFAULT 112,
ADD COLUMN "height" DOUBLE PRECISION NOT NULL DEFAULT 112,
ADD COLUMN "rotation" DOUBLE PRECISION NOT NULL DEFAULT 0;
